.TH programmers.party 7 2022-03-12 GNU

.SH NAME
programmers.party - collective of programmers

.SH DESCRIPTION
.B programmers.party 
is a collective of programmers. This is a collective of software scientists who enjoy the art of software development. There is no lower or upper bound of knowledge required to participate, just a demonstrated ability to try and keep trying.

.SH JOINING
There is only one requirement to join the collective. You must have a willingness to try and to keep trying even after failing. If you feel that this describes you then you should reach out to an existing member of the collective and introduce yourself. In a way this is your first chance to demonstrate your ability to try when the solution is not obvious. I believe in you

.SH MEMBERS
manila, you?

.SH SEE ALSO
.BR https://hhacker.space